name: tls-gw
volumes:
  caddydata:
services:
  web:
    container_name: dn42-personal-site
    image: docker.io/library/caddy:latest
    environment:
      - "ACME_CONTACT_EMAIL=i@exploro.one"
    network_mode: "ns:/run/netns/svcs"
    dns:
      - "fdda:8ca4:1556:3000::8376:bf72"
    volumes:
      - "./caddy.json:/caddy.json:ro"
      - "./dn42-root-ca.crt:/dn42-root-ca.crt:ro"
      - "caddydata:/caddydata"
    command:
      - "caddy"
      - "run"
      - "--config=/caddy.json"
# memo:
# vie1 host interconnect:
#   container (netns svcs): fdda:8ca4:1556:3000::8376:bf73/127
#   host: fdda:8ca4:1556:3000::8376:bf72/127
# vie1-fra1 interconnect:
#   vie1: fdda:8ca4:1556:3000::8376:bf71/127
#   fra1: fdda:8ca4:1556:3000::8376:bf70/127
# statis routes:
# in vie1 host: fd42:d42:d42:54::1/127 via fdda:8ca4:1556:3000::8376:bf73
# in vie1 container: fd00::/8 via fdda:8ca4:1556:3000::8376:bf70
# in fra1: fdda:8ca4:1556:3000::8376:bf72/127 via fdda:8ca4:1556:3000::8376:bf71
# enable all ipv6 forwarding
